### ISSUE TITLE
Steep performance hit after zooming in

### ISSUE THREAD

**Issue by Manueljlin** [penpot/penpot#1014]
**Describe the bug**
When there's a few objects in a Penpot file and you zoom a bit, performance takes a big hit

**To Reproduce**
1. Add a few objects
2. Move/zoom in the canvas

**Expected behavior**
Be a bit smoother

**Video**
https://youtu.be/SQTYU_kH8eI

**Desktop:**

Operating System: openSUSE Tumbleweed 20210601
KDE Plasma Version: 5.21.5
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-10510U CPU @ 1.80GHz
Memory: 15.4 GiB of RAM
Graphics Processor: GeForce MX250/PCIe/SSE2
Browser: Vivaldi 3.8.2259.42 (Stable channel) (64-bit)

**Environment (please complete the following information):**
SaaS version

**Comment by claragvinola** [comment]
Hi Manueljlin! A few days ago we've been making some adjustments for the new release, that maybe affect performance... We think it's already fixed now. :)

**Comment by Manueljlin** [comment]
> Hi Manueljlin! A few days ago we've been making some adjustments for the new release, that maybe affect performance... We think it's already fixed now. :)

It improved quite a bit but it still has some issues. The recording was made the same day this issue was created.

**Comment by soultipsy** [comment]
This problem still exists,  the cause of the lag is mainly the use of shadows and blur effects.
When objects use shadows or blurring effects, and zooming the screen to 2000% or higher, CPU usage will increase dramatically when dragging the screen, and significant lag will occur.

**Comment by Alotor** [comment]
@soultipsy yeah, you're right. The main problem with this is that is a browser SVG implementation matter, depends even if you're using GPU acceleration etc.. basically the blur penalizes the composition by a lot (shadows are using blur as well under the hood).

We have yet to see if we can do something about it like maybe use canvas for the shadows when you're in a big zoom.

**Comment by andymason** [comment]
I recently ran into this issue and have a proposed improvement.

When zoom is >100% set the CSS parameter [`image-rendering` to `optimizespeed`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/image-rendering), this uses nearest neighbour scaling greatly improving performance, and has the additional benefit of matching the pixel grid more closely.

**Comment by Awendel** [comment]
https://github.com/penpot/penpot/issues/2492

offers a possible fix to this if we manage to get the CSS property into the web standard.
Pixel-density could be lowered during an animation / zoom in and then increased back to 100% when completed.

**Comment by Manueljlin** [comment]
I recently read a [blog post](https://zed.dev/blog/videogame) made by the Zed editor developers, where they're talking about how they optimized their custom UI framework.

One thing that caught my eye is that, in the `Drop shadows` section, they [link to another post](https://madebyevan.com/shaders/fast-rounded-rectangle-shadows/) made by Figma's co-founder who made the quick shadow technique they're using. He talks about how box shadows in the browsers are all rendered in the CPU and then given to the GPU to compose it together with the rest of the UI, and gives a few cc0/public domain code snippets about how he went about optimizing this. 

Not sure if this would actually useful for Penpot really, but it's pretty interesting nonetheless.

**Comment by AzazelN28** [comment]
@Manueljlin Thanks! I've read the articles (both zed's and evan wallace's) and they are very good. Right now we are considering whether to write our own document renderer, precisely to be able to implement this kind of optimizations and not rely so much on the browser renderer.

**Comment by Beryesa** [comment]
Sorry for the noise, is there any progress on this?

**Comment by stephane-klein** [comment]
Same issue here, on Fedora 38 and Firefox 118.

**Comment by soulis-1256** [comment]
How come there is no option to limit the zoom levels yet? Anything above 2000% (on my system) is unusable. Being able to limit the max zoom to something like 1500% will vastly improve my experience with penpot.

**Comment by soultipsy** [comment]
Any color gradient will cause performance degradation, including any gradient fills (color or transparency, or even gradients between the same colors), shadows and blurs, gradient images, etc.    This depends on the proportion of the screen window occupied by the gradient, when the gradient part of the window occupies half of the range, the performance will be sharply reduced, reflected in the operation of the zoom will become lagging.    Trying to create a 1000*1000 rectangle and adding a 200 blur to it causes lag even at 100% zoom as long as it is in the center of the window.
This greatly limits my creative range.    I only dare to draw my interface using solid colors because zooming in and out to fine-tune the interface is a very frequent operation, and once the gradient area takes over my window, the program annoyingly stutters, which is really frustrating.

**Comment by Manueljlin** [comment]
They're actively looking to rewrite parts of Penpot in WASM, [and are searching for an expert to hire](https://blog.kaleidos.net/software-engineer/), so we just need a tiny bit more patience on this 😄
