### ISSUE TITLE
The selection area of the content is always larger than its actual area

### ISSUE THREAD

**Issue by soultipsy** [penpot/penpot#1091]
**Describe the bug**
The selection and click range of the content is larger than the area it actually occupies, and the cursor can select and move the content before it is pointed at, which makes it very easy to select the wrong object when selecting two adjacent contents (I demonstrate this situation in the second half of the video).

**To Reproduce**
1.  Create an element (rectangle, circle or other)
2.  Cursor close to the element
3.  When the cursor is a certain distance from the element and not yet in the actual area of the element, the element can be selected and moved

**Expected behavior**

The trigger range of the element selection should be the same as its actual display area and should be able to be selected precisely.

**Screenshots**

https://user-images.githubusercontent.com/40300919/125751404-2b8e0b12-b753-48dc-afb5-4f94b6a13ab1.mp4

**Desktop (please complete the following information):**

-   OS: Windows
-   Browser : Firefox&Microsoft Edge
-   Version :89.02& 92.0.902.45 Beta

**Environment (please complete the following information):**
SAAS (https://design.penpot.app)

**Comment by Alotor** [comment]
Hi @soultipsy we released a new version yesterday and I did a fix related to this. Can you confirm that this issue is happening with the current version? 
Thanks!

**Comment by soultipsy** [comment]
I used https://design.penpot.app, the current version is 1.7.0-alpha-5594-ga6d156438, this problem still exists，When the cursor is 1-2 pixels away from the element, it still triggers
![Snipaste_2021-07-15_16-35-04](https://user-images.githubusercontent.com/40300919/125756639-a81c81c1-19f6-4ed0-90d3-514673205496.png)

**Comment by Alotor** [comment]
Can you share with me the dimensions of the square in the video and the zoom?

The hover/selection has a "selection square" surrounding the cursor because it's easier to select things like lines that otherwise would be very hard to select if we use just one point. So the behaviour you're showing is normal but should be more subtle.

**Comment by soultipsy** [comment]
Yes, I had suspected that this was a problem with the control area, but in reality the size of this range is uncertain, in most cases the cursor triggers at a distance of 1.4px, in a few cases 0.4px, and in some extreme cases there may be a difference of tens of pixels (see videos 1, 2).
These pixel deviations seem to be random and irregular, not only in different pages of the same file will appear different distances (see video 1), even after switching pages, the distance will change (see video 3), very strange.

https://user-images.githubusercontent.com/40300919/125781282-f1b9e245-b469-429b-8ad0-75f6ae008081.mp4


https://user-images.githubusercontent.com/40300919/125781322-b8b8c1af-c0f2-4ca8-909c-090bdd0f4aa1.mp4


https://user-images.githubusercontent.com/40300919/125781328-5f2fb5fb-6a1e-4615-ba81-469549a70cad.mp4

**Comment by myfunnyandy** [comment]
Fixed
