### ISSUE TITLE
Make functionality of ruler tool icon more obvious.

### ISSUE THREAD

**Issue by studiospring** [penpot/penpot#50]
The function of the ruler icon is not clear. It is currently next to the grid icon which shows/hides the grid, which suggests that the ruler icon shows/hides the x-y axis page rulers (it actually measures distances between 2 points). The location, icon, etc should be improved to make the function clearer.
See issue #48 for an example of confusion!
![ruler_on](https://cloud.githubusercontent.com/assets/4901306/23302060/f3ea8462-fa84-11e6-835f-f74a5d85eb8c.jpg)

**Comment by niwinz** [comment]
Fixed on master

**Comment by studiospring** [comment]
Thanks. The old ruler tooltip next to the cursor still shows though. (In the image the cursor is missing because of the screenshot tool).
![ruler](https://cloud.githubusercontent.com/assets/4901306/23533604/e7fa0128-0006-11e7-8daa-5e99d0909332.jpg)

**Comment by studiospring** [comment]
Also, when the ruler is hidden, the left border of the canvas disappears.
![border](https://cloud.githubusercontent.com/assets/4901306/23533987/1f0e073e-0009-11e7-8dce-71c79bf2c7c6.jpg)

**Comment by studiospring** [comment]
Also, the measure tool (not the ruler tool!) does not inactivate after one use, I can use it multiple times without reselecting the tool. This is how I prefer it, but all the other tools can only be used once, which is inconsistent. Should I open another issue?

![ruler2](https://cloud.githubusercontent.com/assets/4901306/23534237/a6c7d762-000a-11e7-8af5-2ec809bb23cd.gif)

**Comment by studiospring** [comment]
Another very minor issue is the y-axis ruler is opaque (stays grey regardless of where the canvas is), but the x-axis ruler is transparent. Maybe transparent is better for more canvas area?
![ruler3](https://cloud.githubusercontent.com/assets/4901306/23536052/8cf6f820-0016-11e7-9962-4a65188c30a2.jpg)
