### ISSUE TITLE
Custom fonts not properly rendered on export

### ISSUE THREAD

**Issue by burnoutberni** [penpot/penpot#994]
**Describe the bug**
When exporting a shape to e.g. PNG, the custom font is apparently not found. Instead a fallback font is used, which shouldn't be the case.

**To Reproduce**
1.  Import custom font
2.  Create shape with that font
3.  Export shape
4.  Open the exported file and compare with sketch

**Expected behavior**
Custom fonts should be exported as visible in the sketch.

**Screenshots**
Sketch:
![Screenshot from 2021-05-28 19-05-47](https://user-images.githubusercontent.com/1640933/120018645-c21d9000-bfe7-11eb-842d-f19860d677ac.png)

Exported file:
![Shareable (quadratisch)](https://user-images.githubusercontent.com/1640933/120018617-b336dd80-bfe7-11eb-81c7-3987ef087030.png)

**Desktop (please complete the following information):**

-   OS: Arch Linux
-   Browser: Firefox
-   Version: 88

**Environment (please complete the following information):**
SAAS (https://design.penpot.app)

**Comment by myfunnyandy** [comment]
Thank you very much for raising this issue. You can check its progress on Taiga from now on: https://tree.taiga.io/project/penpot/issue/1751

**Comment by niwinz** [comment]
Should be fixed

**Comment by burnoutberni** [comment]
Works like a charm, thank you!

**Comment by 100tomer** [comment]
It's possible this issue still happening to someone? For me it happens on every PNG export

**Comment by Stzyxh** [comment]
I have the same issue again, but not only with custom fonts @myfunnyandy

**Comment by myfunnyandy** [comment]
@Stzyxh could you provide an example or the steps to reproduce it? I've exported text layers (one custom and one from the base catalog) from design.penpot.app in png format and couldn't reproduce the issue.

If you don't feel more comfortable sharing a file in public you can send it to support@penpot.app.

**Comment by Stzyxh** [comment]
@myfunnyandy Interesting, when I downloaded it on my laptop the svg seemed to be normal, besides that the text got bigger. But now...
the image above is the png

![Image](https://github.com/user-attachments/assets/398c9d82-6c95-49f3-b25f-60c8b25db85f)
![Image](https://github.com/user-attachments/assets/e1da79b4-0aa1-4c20-9269-4c1d6fc609ba)

**Comment by Stzyxh** [comment]
oh wait is this a device or browser problem? my mobile shows the file fine, but my Laptop doesn't

**Comment by PremiumBurger** [comment]
Same issue here. @myfunnyandy i sent a video on how to reproduce this to support@penpot.app
